// Generated by CoffeeScript 1.3.1
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  define(function(require, exports, module) {
    var $, Tutorial;
    $ = require('jQuery');
    Tutorial = (function() {
      var current;

      Tutorial.name = 'Tutorial';

      Tutorial.prototype.steps = null;

      Tutorial.prototype.className = 'tutorial';

      Tutorial.prototype.message = null;

      Tutorial.prototype.underlay = null;

      current = -1;

      function Tutorial(_arg) {
        this.el = _arg.el, this.steps = _arg.steps;
        this.end = __bind(this.end, this);

        this.next = __bind(this.next, this);

        this.start = __bind(this.start, this);

        if (this.steps == null) {
          this.steps = [];
        }
        this.underlay = $('<div></div>');
        this.underlay.addClass('underlay');
        this.underlay.appendTo(this.el);
        this.message = $('<div></div>');
        this.message.addClass('step');
        this.message.appendTo(this.el);
      }

      Tutorial.prototype.start = function() {
        this.message.add(this.underlay).css({
          display: ''
        });
        this.current = -1;
        return this.next();
      };

      Tutorial.prototype.next = function(e) {
        if (e != null) {
          e.stopPropagation();
        }
        if (!!~this.current) {
          this.steps[this.current].leave();
        }
        this.current += 1;
        if (this.steps[this.current]) {
          return this.steps[this.current].enter(this);
        } else {
          return this.end();
        }
      };

      Tutorial.prototype.end = function() {
        return this.message.add(this.underlay).css({
          display: 'none'
        });
      };

      return Tutorial;

    })();
    Tutorial.Step = (function() {

      Step.name = 'Step';

      Step.prototype.content = '';

      Step.prototype.modal = false;

      Step.prototype.style = null;

      Step.prototype.attach = null;

      Step.prototype.className = '';

      Step.prototype.nextOn = '';

      Step.prototype.tutorial = null;

      function Step(_arg) {
        this.content = _arg.content, this.style = _arg.style, this.attach = _arg.attach, this.nextOn = _arg.nextOn, this.className = _arg.className;
        this.leave = __bind(this.leave, this);

        this.enter = __bind(this.enter, this);

      }

      Step.prototype.enter = function(tutorial) {
        var buttonsHolder, eventName, selector, _ref;
        this.tutorial = tutorial;
        this.tutorial.message.html("<p>" + (this.content.join('</p><p>')) + "</p>");
        if (this.nextOn) {
          _ref = this.nextOn;
          for (eventName in _ref) {
            selector = _ref[eventName];
            $(document).on(eventName, selector, this.tutorial.next);
          }
        } else {
          buttonsHolder = $('<div class="continue"><button>Next</button></div>');
          this.tutorial.message.append(buttonsHolder);
          this.tutorial.message.on('click', '.continue button', this.tutorial.next);
        }
        if (this.style) {
          this.tutorial.message.css(this.style);
        }
        if (this.attach) {
          this.move(this.attach.x, this.attach.y, this.attach.to, this.attach.at.x, this.attach.at.y);
        }
        if (this.className) {
          return this.tutorial.message.addClass(this.className);
        }
      };

      Step.prototype.move = function(stepX, stepY, target, targetX, targetY) {
        var stepOffset, stepSize, targetOffset, targetSize, xStrings, yStrings;
        xStrings = {
          left: 0,
          center: 0.5,
          right: 1
        };
        yStrings = {
          top: 0,
          middle: 0.5,
          bottom: 1
        };
        if (stepX in xStrings) {
          stepX = xStrings[stepX];
        }
        if (stepY in yStrings) {
          stepY = yStrings[stepY];
        }
        if (targetX in xStrings) {
          targetX = xStrings[targetX];
        }
        if (targetY in yStrings) {
          targetY = yStrings[targetY];
        }
        target = $(target).first();
        targetSize = {
          width: target.width(),
          height: target.height()
        };
        targetOffset = target.offset();
        stepSize = {
          width: this.tutorial.message.width(),
          height: this.tutorial.message.height()
        };
        stepOffset = {
          left: targetOffset.left - (stepSize.width * stepX) + (targetSize.width * targetX),
          top: targetOffset.top - (stepSize.height * stepY) + (targetSize.height * targetY)
        };
        return this.tutorial.message.css(stepOffset);
      };

      Step.prototype.leave = function() {
        var eventName, selector, _ref;
        this.tutorial.message.html('');
        if (this.nextOn) {
          _ref = this.nextOn;
          for (eventName in _ref) {
            selector = _ref[eventName];
            $(document).off(eventName, selector, this.tutorial.next);
          }
        } else {
          this.tutorial.message.off('click', '.continue button', this.tutorial.next);
        }
        if (this.className) {
          return this.tutorial.message.removeClass(this.className);
        }
      };

      return Step;

    })();
    if ((module != null ? module.exports : void 0) != null) {
      return module.exports = Tutorial;
    } else {
      return window.Tutorial = Tutorial;
    }
  });

}).call(this);
