// Generated by CoffeeScript 1.3.2
(function() {
  var Spectrogram, Subject,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Subject = require('zooniverse/models/Subject');

  Spectrogram = (function(_super) {

    __extends(Spectrogram, _super);

    function Spectrogram() {
      return Spectrogram.__super__.constructor.apply(this, arguments);
    }

    return Spectrogram;

  })(Subject);

  module.exports = Spectrogram;

}).call(this);
