server: python -m SimpleHTTPServer $ZOO_SERVER_PORT
login_coffee: coffee --compile --watch src/scripts/lib/zooniverse/proxy
main_coffee: coffee --compile --output scripts --watch src/scripts/lib/zooniverse/main.coffee
src_coffee: coffee --compile --output scripts --watch src/scripts
src_sass:   sass --watch src/styles:styles --require bourbon --no-cache --debug-info
zoo_sass:   sass --watch src/scripts/lib/zooniverse/styles/main.scss:styles/zooniverse.css --no-cache --debug-info
