// Generated by CoffeeScript 1.3.2
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(function(require, exports, module) {
    var CurrentSubjectInfo, Spine;
    Spine = require('Spine');
    CurrentSubjectInfo = (function(_super) {

      __extends(CurrentSubjectInfo, _super);

      function CurrentSubjectInfo() {
        return CurrentSubjectInfo.__super__.constructor.apply(this, arguments);
      }

      return CurrentSubjectInfo;

    })(Spine.Controller);
    return module.exports = CurrentSubjectInfo;
  });

}).call(this);
