// Generated by CoffeeScript 1.3.2
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(function(require, exports, module) {
    var Spectrogram, SpectrogramClassifier, Workflow;
    Workflow = require('zooniverse/controllers/Workflow');
    Spectrogram = require('models/Spectrogram');
    SpectrogramClassifier = (function(_super) {

      __extends(SpectrogramClassifier, _super);

      function SpectrogramClassifier() {
        return SpectrogramClassifier.__super__.constructor.apply(this, arguments);
      }

      return SpectrogramClassifier;

    })(Workflow);
    return module.exports = SpectrogramClassifier;
  });

}).call(this);
